

CREATE TABLE dbo.TEMP_VACCINATION_DATA
(
	NAME VARCHAR(255),
	Cust_I VARCHAR(50) NOT NULL PRIMARY KEY,
	Open_Dt DATETIME,
	Consul_Dt DATETIME,
	VAC_ID VARCHAR(50),
	DR_Name VARCHAR(255),
	State VARCHAR(50),
	Country VARCHAR(50),
	DOB DATETIME,
	FLAG  VARCHAR(1),
	load_dt datetime
);

